security:
    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~
            #http_basic:
            #   realm: "Secured Demo Area"

    access_control:
        #- {path: ^/area_restrita, roles: ROLE_USER}

    providers:
        bd_noticiaunimed:
            entity: { class: NoticiaBundle:User, property: username }

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        NoticiaBundle\Entity\User: sha512