<?php

namespace NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NoticiaBundle\Entity\Categoria;

/**
 * CategoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{

    public function adicionar(Categoria $categoria) {

        $this->_em->persist($categoria);
        $this->_em->flush();
        return true;
    }

    public function excluir(Categoria $categoria) {
        $this->_em->remove($categoria);
        $this->_em->flush();
        return true;
    }

    public function alterar(Categoria $categoria) {
        $this->_em->merge($categoria);
        $this->_em->flush();
        return true;
    }
}
