<?php

namespace NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NoticiaBundle\Entity\Historico;

/**
 * HistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoRepository extends EntityRepository
{

    public function adicionar(Historico $historico) {

        $this->_em->persist($historico);
        $this->_em->flush();
        return true;
    }

    public function buscaTodos($limit = null)
    {
        $qb = $this->createQueryBuilder('h')
                    ->select('h.noticiaId, h.noticiaNome')->distinct()
                    ->addOrderBy('h.data', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function buscarHistorcoEspecifico($noticiaId)
    {
        $qb = $this->createQueryBuilder('h')
                    ->select('h')
                    ->where('h.noticiaId = :noticiaId')
                    ->setParameter('noticiaId', $noticiaId)
                    ->orderBy('h.data','desc');

        return $qb->getQuery()->getResult();

    }

}
