<?php

namespace NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use NoticiaBundle\Entity\Historico;

/**
 * HistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoRepository extends EntityRepository
{

    public function adicionar(Historico $historico) {

        $this->_em->persist($historico);
        $this->_em->flush();
        return true;
    }

}
