<?php

namespace NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagemRepository extends EntityRepository
{
}
