<?php

namespace NoticiaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Proxies\__CG__\NoticiaBundle\Entity\Noticia;

/**
 * NoticiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiaRepository extends EntityRepository
{

    public function buscaNoticiaPorData($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.dtCadastro', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function adicionar(Noticia $noticia) {

        $this->_em->persist($noticia);
        $this->_em->flush();
        return true;

    }

}
